using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
// ReSharper disable InconsistentNaming
// ReSharper disable MemberHidesStaticFromOuterClass
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Elision.Feature.Library.Seo.SC.Integration
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{035D7D88-5A24-41D8-8D5F-CDDFF0397295}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta</description></item>
        /// </list>
        /// </summary>
        public struct _TwitterCardsMeta
        {
            public static readonly ID TemplateId = new ID("{035D7D88-5A24-41D8-8D5F-CDDFF0397295}");
            public const string Name = "_TwitterCardsMeta";

            public struct FieldIds
            {
                /// <summary>
                /// <para>@username of content creator</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{F4DED7B3-8B6F-46D8-902C-1C119BDA1699}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardContentCreator</description></item>
                /// </list>
                /// </summary>
                public static readonly ID TwitterCardContentCreator = new ID("{F4DED7B3-8B6F-46D8-902C-1C119BDA1699}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{5B3DD1A3-40F8-42BE-900E-53FA38195AF1}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardDescription</description></item>
                /// </list>
                /// </summary>
                public static readonly ID TwitterCardDescription = new ID("{5B3DD1A3-40F8-42BE-900E-53FA38195AF1}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Image</description></item>
                ///     <item><term>Field ID:</term><description>{BA3C147E-035B-478F-829B-FE233775648F}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardImage</description></item>
                /// </list>
                /// </summary>
                public static readonly ID TwitterCardImage = new ID("{BA3C147E-035B-478F-829B-FE233775648F}");
                /// <summary>
                /// <para>The Twitter @username the card should be attributed to.</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{BA005D3B-393D-4594-8508-70A503925DCD}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardSite</description></item>
                /// </list>
                /// </summary>
                public static readonly ID TwitterCardSite = new ID("{BA005D3B-393D-4594-8508-70A503925DCD}");
                /// <summary>
                /// <para>Same as Site, but the user’s Twitter ID instead of the website's Twitter ID.</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{217988BC-4DDE-4B44-A688-DFB8F69C6061}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardSiteId</description></item>
                /// </list>
                /// </summary>
                public static readonly ID TwitterCardSiteId = new ID("{217988BC-4DDE-4B44-A688-DFB8F69C6061}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{0181FE49-A838-496D-8690-935282E599F3}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardTitle</description></item>
                /// </list>
                /// </summary>
                public static readonly ID TwitterCardTitle = new ID("{0181FE49-A838-496D-8690-935282E599F3}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplist</description></item>
                ///     <item><term>Field ID:</term><description>{579ED843-06B5-4E31-9B98-0D4B12E418AB}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardType</description></item>
                /// </list>
                /// </summary>
                public static readonly ID TwitterCardType = new ID("{579ED843-06B5-4E31-9B98-0D4B12E418AB}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <para>@username of content creator</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{F4DED7B3-8B6F-46D8-902C-1C119BDA1699}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardContentCreator</description></item>
                /// </list>
                /// </summary>
                public const string TwitterCardContentCreator = "TwitterCardContentCreator";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{5B3DD1A3-40F8-42BE-900E-53FA38195AF1}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardDescription</description></item>
                /// </list>
                /// </summary>
                public const string TwitterCardDescription = "TwitterCardDescription";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Image</description></item>
                ///     <item><term>Field ID:</term><description>{BA3C147E-035B-478F-829B-FE233775648F}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardImage</description></item>
                /// </list>
                /// </summary>
                public const string TwitterCardImage = "TwitterCardImage";
                /// <summary>
                /// <para>The Twitter @username the card should be attributed to.</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{BA005D3B-393D-4594-8508-70A503925DCD}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardSite</description></item>
                /// </list>
                /// </summary>
                public const string TwitterCardSite = "TwitterCardSite";
                /// <summary>
                /// <para>Same as Site, but the user’s Twitter ID instead of the website's Twitter ID.</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{217988BC-4DDE-4B44-A688-DFB8F69C6061}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardSiteId</description></item>
                /// </list>
                /// </summary>
                public const string TwitterCardSiteId = "TwitterCardSiteId";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{0181FE49-A838-496D-8690-935282E599F3}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardTitle</description></item>
                /// </list>
                /// </summary>
                public const string TwitterCardTitle = "TwitterCardTitle";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplist</description></item>
                ///     <item><term>Field ID:</term><description>{579ED843-06B5-4E31-9B98-0D4B12E418AB}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_TwitterCardsMeta/Twitter Card/TwitterCardType</description></item>
                /// </list>
                /// </summary>
                public const string TwitterCardType = "TwitterCardType";
            }
		}
    }
}
namespace Elision.Feature.Library.Seo.SC.Integration
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{27F032BB-8130-43B2-8E5D-7F63B000D2F6}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_SiteMetaFields</description></item>
        /// </list>
        /// </summary>
        public struct _SiteMetaFields
        {
            public static readonly ID TemplateId = new ID("{27F032BB-8130-43B2-8E5D-7F63B000D2F6}");
            public const string Name = "_SiteMetaFields";

            public struct FieldIds
            {
                /// <summary>
                /// <para>This value is appended to the browser title for every page on the site</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{8E87381A-CCA5-4EC4-98B4-CC39023C6503}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_SiteMetaFields/Metadata/BrowserTitleSuffix</description></item>
                /// </list>
                /// </summary>
                public static readonly ID BrowserTitleSuffix = new ID("{8E87381A-CCA5-4EC4-98B4-CC39023C6503}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <para>This value is appended to the browser title for every page on the site</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{8E87381A-CCA5-4EC4-98B4-CC39023C6503}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_SiteMetaFields/Metadata/BrowserTitleSuffix</description></item>
                /// </list>
                /// </summary>
                public const string BrowserTitleSuffix = "BrowserTitleSuffix";
            }
		}
    }
}
namespace Elision.Feature.Library.Seo.SC.Integration
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{359D47A4-7DD7-465B-9060-04020CC90386}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta</description></item>
        /// </list>
        /// </summary>
        public struct _OpenGraphMeta
        {
            public static readonly ID TemplateId = new ID("{359D47A4-7DD7-465B-9060-04020CC90386}");
            public const string Name = "_OpenGraphMeta";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{475A8C93-A6CB-4D6B-A288-58FD09FB7A18}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgDescription</description></item>
                /// </list>
                /// </summary>
                public static readonly ID OgDescription = new ID("{475A8C93-A6CB-4D6B-A288-58FD09FB7A18}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Image</description></item>
                ///     <item><term>Field ID:</term><description>{F046BEA2-BB06-4CEB-B87D-2F1A28A6D101}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgImage</description></item>
                /// </list>
                /// </summary>
                public static readonly ID OgImage = new ID("{F046BEA2-BB06-4CEB-B87D-2F1A28A6D101}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{15D1129E-D78D-4EE4-A005-0CC1617A5F4D}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgSiteName</description></item>
                /// </list>
                /// </summary>
                public static readonly ID OgSiteName = new ID("{15D1129E-D78D-4EE4-A005-0CC1617A5F4D}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{9CE2BFC9-04C1-429C-B388-152506E97078}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgTitle</description></item>
                /// </list>
                /// </summary>
                public static readonly ID OgTitle = new ID("{9CE2BFC9-04C1-429C-B388-152506E97078}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{4E4F0C39-6B77-43F5-AB56-8AEFAA395819}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgType</description></item>
                /// </list>
                /// </summary>
                public static readonly ID OgType = new ID("{4E4F0C39-6B77-43F5-AB56-8AEFAA395819}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{475A8C93-A6CB-4D6B-A288-58FD09FB7A18}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgDescription</description></item>
                /// </list>
                /// </summary>
                public const string OgDescription = "OgDescription";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Image</description></item>
                ///     <item><term>Field ID:</term><description>{F046BEA2-BB06-4CEB-B87D-2F1A28A6D101}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgImage</description></item>
                /// </list>
                /// </summary>
                public const string OgImage = "OgImage";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{15D1129E-D78D-4EE4-A005-0CC1617A5F4D}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgSiteName</description></item>
                /// </list>
                /// </summary>
                public const string OgSiteName = "OgSiteName";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{9CE2BFC9-04C1-429C-B388-152506E97078}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgTitle</description></item>
                /// </list>
                /// </summary>
                public const string OgTitle = "OgTitle";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{4E4F0C39-6B77-43F5-AB56-8AEFAA395819}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_OpenGraphMeta/Open Graph Data/OgType</description></item>
                /// </list>
                /// </summary>
                public const string OgType = "OgType";
            }
		}
    }
}
namespace Elision.Feature.Library.Seo.SC.Integration
{
    public partial struct Renderings
    {
        public partial struct Seo
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>Rendering ID:</term><description>{422BF485-564D-460D-8F7A-E708C4DA9118}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/layout/Renderings/Feature/Elision/ElisionFeatureLibrarySeo/Seo/TwitterCardMeta</description></item>
            /// </list>
            /// </summary>
            public static readonly ID TwitterCardMeta = new ID("{422BF485-564D-460D-8F7A-E708C4DA9118}");
        }
    }
}
namespace Elision.Feature.Library.Seo.SC.Integration
{
    public partial struct Renderings
    {
        public partial struct Seo
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>Rendering ID:</term><description>{459D9770-0CDE-4865-9E46-6A73836A9BB1}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/layout/Renderings/Feature/Elision/ElisionFeatureLibrarySeo/Seo/PageMetadata</description></item>
            /// </list>
            /// </summary>
            public static readonly ID PageMetadata = new ID("{459D9770-0CDE-4865-9E46-6A73836A9BB1}");
        }
    }
}
namespace Elision.Feature.Library.Seo.SC.Integration
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{4B16534B-BC1B-4CD5-B62C-440F0AE2D842}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_RobotsContent</description></item>
        /// </list>
        /// </summary>
        public struct _RobotsContent
        {
            public static readonly ID TemplateId = new ID("{4B16534B-BC1B-4CD5-B62C-440F0AE2D842}");
            public const string Name = "_RobotsContent";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A0BA03BF-1357-4A78-B1E6-378CED331B5E}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_RobotsContent/Robots/RobotsContent</description></item>
                /// </list>
                /// </summary>
                public static readonly ID RobotsContent = new ID("{A0BA03BF-1357-4A78-B1E6-378CED331B5E}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A0BA03BF-1357-4A78-B1E6-378CED331B5E}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_RobotsContent/Robots/RobotsContent</description></item>
                /// </list>
                /// </summary>
                public const string RobotsContent = "RobotsContent";
            }
		}
    }
}
namespace Elision.Feature.Library.Seo.SC.Integration
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{6F0FABD4-47AB-461A-959E-B4D292EE01E5}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields</description></item>
        /// </list>
        /// </summary>
        public struct _PageMetaFields
        {
            public static readonly ID TemplateId = new ID("{6F0FABD4-47AB-461A-959E-B4D292EE01E5}");
            public const string Name = "_PageMetaFields";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Checkbox</description></item>
                ///     <item><term>Field ID:</term><description>{0ED18C8B-E06A-4F49-8F9E-8346F1A3294C}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/BlockSearchEngineIndexing</description></item>
                /// </list>
                /// </summary>
                public static readonly ID BlockSearchEngineIndexing = new ID("{0ED18C8B-E06A-4F49-8F9E-8346F1A3294C}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Checkbox</description></item>
                ///     <item><term>Field ID:</term><description>{7FB8D83D-C981-49D9-B352-953E5C6BE7CF}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/BlockSearchEngineLinkFollowing</description></item>
                /// </list>
                /// </summary>
                public static readonly ID BlockSearchEngineLinkFollowing = new ID("{7FB8D83D-C981-49D9-B352-953E5C6BE7CF}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{D6CB41B5-9467-4C42-95AC-B62584A1F5F0}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/BrowserTitle</description></item>
                /// </list>
                /// </summary>
                public static readonly ID BrowserTitle = new ID("{D6CB41B5-9467-4C42-95AC-B62584A1F5F0}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{C0AD316F-EEC8-494D-A30A-356C10E8853E}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/CanonicalUrl</description></item>
                /// </list>
                /// </summary>
                public static readonly ID CanonicalUrl = new ID("{C0AD316F-EEC8-494D-A30A-356C10E8853E}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{D62C4448-2E23-4393-939D-F489DCFB881E}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/MetaDescription</description></item>
                /// </list>
                /// </summary>
                public static readonly ID MetaDescription = new ID("{D62C4448-2E23-4393-939D-F489DCFB881E}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{DEAD7283-98C8-4AB8-924E-0DEB00858EFB}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/MetaKeywords</description></item>
                /// </list>
                /// </summary>
                public static readonly ID MetaKeywords = new ID("{DEAD7283-98C8-4AB8-924E-0DEB00858EFB}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Checkbox</description></item>
                ///     <item><term>Field ID:</term><description>{0ED18C8B-E06A-4F49-8F9E-8346F1A3294C}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/BlockSearchEngineIndexing</description></item>
                /// </list>
                /// </summary>
                public const string BlockSearchEngineIndexing = "BlockSearchEngineIndexing";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Checkbox</description></item>
                ///     <item><term>Field ID:</term><description>{7FB8D83D-C981-49D9-B352-953E5C6BE7CF}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/BlockSearchEngineLinkFollowing</description></item>
                /// </list>
                /// </summary>
                public const string BlockSearchEngineLinkFollowing = "BlockSearchEngineLinkFollowing";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{D6CB41B5-9467-4C42-95AC-B62584A1F5F0}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/BrowserTitle</description></item>
                /// </list>
                /// </summary>
                public const string BrowserTitle = "BrowserTitle";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{C0AD316F-EEC8-494D-A30A-356C10E8853E}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/CanonicalUrl</description></item>
                /// </list>
                /// </summary>
                public const string CanonicalUrl = "CanonicalUrl";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{D62C4448-2E23-4393-939D-F489DCFB881E}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/MetaDescription</description></item>
                /// </list>
                /// </summary>
                public const string MetaDescription = "MetaDescription";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{DEAD7283-98C8-4AB8-924E-0DEB00858EFB}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Base/_PageMetaFields/Metadata/MetaKeywords</description></item>
                /// </list>
                /// </summary>
                public const string MetaKeywords = "MetaKeywords";
            }
		}
    }
}
namespace Elision.Feature.Library.Seo.SC.Integration
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{A42909C1-539E-46E4-9F1F-DB999603D6DE}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Feature/Elision/ElisionFeatureLibrarySeo/Options/TwitterCardType</description></item>
        /// </list>
        /// </summary>
        public struct TwitterCardType
        {
            public static readonly ID TemplateId = new ID("{A42909C1-539E-46E4-9F1F-DB999603D6DE}");
            public const string Name = "TwitterCardType";

		}
    }
}
